#!/bin/bash

/usr/bin/rofi -show run \
    -bw 5 \
    -color-enabled true \
    -font "Noto Sans 12" \
    -color-window "argb:ee222222, #79a4e5, #79a4e5" \
    -color-normal "argb:00000000, #79a4e5, argb:00000000, #79a4e5, #1b2b34" \
    -color-active "argb:00000000, #6699cc, argb:00000000, #6699cc, #1b2b34" \
    -color-urgent "argb:00000000, #79a4e5, argb:00000000, #79a4e5, #1b2b34" \
    -hide-scrollbar true \
    -line-margin 3 \
    -lines 20 \
    -location 0 \
    -modi "run,ssh" \
    -opacity 85 \
    -padding 3 \
    -separator-style "none" \
    -width 75

