#!/bin/bash

docker run --rm -it -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -e AWS_REGION=$AWS_REGION -v $(pwd)/:/app/ --workdir=/app cloudcloud/k8s-tools:1.11.2 "$@"

